# Generated by Django 3.1.4 on 2020-12-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hello, my name is <django.db.models.query_utils.DeferredAttribute object at 0x1109d3b50>!', max_length=500),
        ),
    ]
